<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="admin_location_update.aspx.cs" Inherits="Default2" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
    <style type="text/css">

        .style1
        {
            width: 100%;
        }
        .style3
        {
            width: 236px;
        }
        .style4
        {
            height: 21px;
            width: 236px;
        }
        .style2
        {
            height: 21px;
        }
        .style5
        {
            width: 236px;
            height: 24px;
        }
        .style6
        {
            height: 24px;
        }
    </style>
    </asp:Content>
   

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <br />
<br />
<br />
<br />
<br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" DataKeyNames="loc_id" 
        DataSourceID="SqlDataSource1" EmptyDataText="No data available ">
        <Columns>
            <asp:BoundField DataField="loc_id" HeaderText="loc_id" ReadOnly="True" 
                SortExpression="loc_id" InsertVisible="False" />
            <asp:BoundField DataField="loc_name" HeaderText="loc_name" 
                SortExpression="loc_name" />
            <asp:CheckBoxField DataField="loc_valid" HeaderText="loc_valid" 
                SortExpression="loc_valid" />
            <asp:BoundField DataField="loc_compCode" HeaderText="loc_compCode" 
                SortExpression="loc_compCode" />
            <asp:BoundField DataField="loc_admin" HeaderText="loc_admin" 
                SortExpression="loc_admin" />
            <asp:CheckBoxField DataField="loc_isDeleted" HeaderText="loc_isDeleted" 
                SortExpression="loc_isDeleted" />
            <asp:BoundField DataField="loc_createdBy" HeaderText="loc_createdBy" 
                SortExpression="loc_createdBy" />
            <asp:BoundField DataField="loc_createdOn" HeaderText="loc_createdOn" 
                SortExpression="loc_createdOn" />
            <asp:BoundField DataField="loc_ModifiedBy" HeaderText="loc_ModifiedBy" 
                SortExpression="loc_ModifiedBy" />
        </Columns>
    </asp:GridView>
&nbsp;
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:InventoryConnectionString %>" 
        DeleteCommand="Delete from t_im_loc_mst where loc_id=@loc_id" 
        SelectCommand="select * from t_im_loc_mst " 
        UpdateCommand="update t_im_loc_mst set loc_id=@ab,loc_name=@cd,loc_valid=@ef,loc_compCode=@gh,loc_admin=@ij,loc_isDeleted=@kl,loc_ModifiedBy=@mn where loc_id=@loc_id

" onselecting="SqlDataSource1_Selecting">
        <DeleteParameters>
            <asp:Parameter Name="loc_id" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="TextBox1" Name="ab" PropertyName="Text" />
            <asp:ControlParameter ControlID="TextBox2" Name="cd" PropertyName="Text" />
            <asp:ControlParameter Name="ef" ControlID="RadioButtonList1" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="TextBox4" Name="gh" PropertyName="Text" />
            <asp:ControlParameter ControlID="TextBox5" Name="ij" PropertyName="Text" />
            <asp:ControlParameter ControlID="RadioButtonList2" Name="kl" 
                PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="TextBox6" Name="mn" PropertyName="Text" />
            <asp:ControlParameter ControlID="GridView1" Name="loc_id" 
                PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<br />
    <asp:Label ID="Label1" runat="server" BorderColor="White" 
        Text="    ENTER THE DATA    " 
        ToolTip="enter data and press the update tab corresponding to the row you want to make changes to"></asp:Label>
<br />
&nbsp;&nbsp;&nbsp;
    <table class="style1">
        <tr>
            <td class="style3">
                Personal No</td>
            <td>
                <asp:TextBox ID="TextBox6" runat="server" Width="200px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" 
                    ControlToValidate="TextBox6" Display="Dynamic" 
                    ErrorMessage="*This field is mandatory" SetFocusOnError="True"></asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td class="style3">
                Location ID:</td>
            <td>
                <asp:TextBox ID="TextBox1" runat="server" Width="200px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                    ControlToValidate="TextBox1" Display="Dynamic" 
                    ErrorMessage="*This field is mandatory"></asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td class="style3">
                Location Name:</td>
            <td>
                <asp:TextBox ID="TextBox2" runat="server" Width="201px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" 
                    ControlToValidate="TextBox2" Display="Dynamic" 
                    ErrorMessage="*This feild is mandatory"></asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td class="style5">
                Location Availability:</td>
            <td class="style6">
                <asp:RadioButtonList ID="RadioButtonList1" runat="server">
                    <asp:ListItem Value="true">Yes</asp:ListItem>
                    <asp:ListItem Value="false">No</asp:ListItem>
                </asp:RadioButtonList>
            </td>
        </tr>
        <tr>
            <td class="style4">
                Company Code:</td>
            <td class="style2">
                <asp:TextBox ID="TextBox4" runat="server" Width="202px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
                    ControlToValidate="TextBox4" Display="Dynamic" 
                    ErrorMessage="*This field is mandatory"></asp:RequiredFieldValidator>
            </td>
        </tr>
        <tr>
            <td class="style3">
                Personal Number of Owner:</td>
            <td>
                <asp:TextBox ID="TextBox5" runat="server" Width="202px"></asp:TextBox>
                <asp:RangeValidator ID="RangeValidator1" runat="server" 
                    ControlToValidate="TextBox5" Display="Dynamic" 
                    ErrorMessage="*the field should be not more than 10 characters" MaximumValue="9999999999" 
                    MinimumValue="0" SetFocusOnError="True"></asp:RangeValidator>
            </td>
        </tr>
        <tr>
            <td class="style4">
                Is Location deleted</td>
            <td class="style2">
                <asp:RadioButtonList ID="RadioButtonList2" runat="server">
                    <asp:ListItem Value="true">Yes</asp:ListItem>
                    <asp:ListItem Value="false">No</asp:ListItem>
                </asp:RadioButtonList>
            </td>
        </tr>
        <tr>
            <td class="style3">
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3">
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td class="style3">
                <asp:Button ID="Button1" runat="server" Text="Submit" />
            </td>
            <td>
                <asp:Button ID="Button2" runat="server" CausesValidation="False" Text="Reset" />
            </td>
        </tr>
    </table>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

























    </asp:Content>

